# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dell\Downloads\抓周\catchweek.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtCore import QTimer, pyqtSignal
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QWidget, QLabel, QApplication
class myLabel(QLabel):
    _signal = pyqtSignal(str)#信号定义
    def __init__(self, parent=None):
        super(myLabel, self).__init__(parent)

    def mousePressEvent(self, e):  ##重载一下鼠标点击事件
            print("you clicked the label")
            self._signal.emit("正在检测中")
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 392)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_1 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_1.setStyleSheet("image: url(:/新前缀/图片1.png);\n"
"")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.gridLayout_2.addWidget(self.label_1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridGroupBox)
        self.label.setStyleSheet("image: url(:/新前缀/embedded (2).jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_7.setStyleSheet("image: url(:/新前缀/搜狗截图20221116125445.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_2.setStyleSheet("image: url(:/新前缀/图片3.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_6.setStyleSheet("image: url(:/新前缀/搜狗截图20221116125318.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_4.setStyleSheet("image: url(:/新前缀/图片5.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_10.setStyleSheet("image: url(:/新前缀/图片8.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_9.setStyleSheet("image: url(:/新前缀/搜狗截图20221116125215.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_5.setStyleSheet("image: url(:/新前缀/图片10.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridGroupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_8.setStyleSheet("image: url(:/新前缀/搜狗截图20221116125413.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_11.setStyleSheet("image: url(:/新前缀/图片2.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 2, 1, 1)
        self.gridLayout.addWidget(self.gridGroupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 22))
        self.menubar.setObjectName("menubar")
        self.menuDon_t_Click = QtWidgets.QMenu(self.menubar)
        self.menuDon_t_Click.setObjectName("menuDon_t_Click")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuDon_t_Click.menuAction())
        self.label=myLabel(self.label)
        self.label_1=myLabel(self.label_1)
        self.label_2=myLabel(self.label_2)
        self.label_11=myLabel(self.label_11)
        self.label_4=myLabel(self.label_4)
        self.label_5=myLabel(self.label_5)
        self.label_6=myLabel(self.label_6)
        self.label_7=myLabel(self.label_7)
        self.label_8=myLabel(self.label_8)
        self.label_9=myLabel(self.label_9)
        self.label_10=myLabel(self.label_10)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def callbacklog(self, msg):
        from PIL import Image
        import matplotlib.pyplot as plt
        img = Image.open(self.lu)
        plt.figure("image")
        plt.imshow(img)
        plt.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "抓周"))
        self.menuDon_t_Click.setTitle(_translate("MainWindow", "Don\'t Click"))




import pic_rc
